### ISSUE TITLE
Geração de índice no servidor de produção resulta em erro de timeout 

### ISSUE THREAD

**Issue by heitorbarbieri** [bireme/NGrams#13]
Geração do índice no servidor diamante12.bireme.br (dedup.bireme.org)

[14:04] Camilo, Ana Katia (BIR)
    <<< 1500000
<<< 1501000
Exception in thread "main" java.net.SocketTimeoutException: Read timed out
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1963)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1958)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1957)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1525)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)

**Comment by heitorbarbieri** [comment]
Chegou-se à conclusão/acordo de que a melhor prática seria a da geração do índice no servidor de processamento (serverofi5) e sua posterior transferência para o servidor de produção (diamante12.bireme.br).
